### ISSUE TITLE
Running locally with Minikube

### ISSUE THREAD

**Issue by zachgrayio** [canhnt/k8s-nats-streaming#1]
I am having trouble getting this running locally with Minikube, although I believe I've correctly configured NFS. 

Just curious if anyone else has had any success running this on Minikube and if so, I'd love to see some details :)

**Comment by canhnt** [comment]
Can you please describe what you have configured NFS to run in minikube, helm command to install the chart and specific errors?

FYI: I haven't tested the chart in minikube yet.
